name: Create Text File
description: Creates a text file very easy (Windows only)
branding:
 logo: 'file-text'
 color: 'blue'
inputs:
  text:
     description: 'The text to include in the file'
     required: true
     default: 'Hello world!'
  filename:
     description: 'The name of the file when saved'
     required: true
     default: 'file.txt'
  path:
     description: 'The path where to place the file'
     required: false
runs:
  using: "composite"
  steps:
    - run: echo $TEXT > ./${{ inputs.path }}/${{ inputs.filename }}
    - run: git config --global user.name '${{ github.REPOSITORY_OWNER }}'
    - run: git config --global user.email '${{ github.REPOSITORY_OWNER }}@users.noreply.github.com'
    - run: git add -A
    - run: git commit -am "Create ${{ inputs.filename }}"
    - run: git push origin ${{ github.REF_NAME }}
      shell: cmd
