name: Create Text File
description: Creates a text file very easy (Windows only)
branding:
 logo: 'file-text'
 color: 'blue'
inputs:
  text:
     description: 'The text to include in the file'
     required: true
     default: 'Hello world!'
  filename:
     description: 'The name of the file when saved'
     required: true
     default: 'file.txt'
runs:
  using: "composite"
  env:
    TEXT: ${{ inputs.text }}
    FILENAME: ${{ inputs.filename }}
  steps:
    - run: echo $TEXT > $FILENAME
    - run: git config --global user.name '$GITHUB_REPOSITORY_OWNER'
    - run: git config --global user.email '$GITHUB_REPOSITORY_OWNER@users.noreply.github.com'
    - run: git add -A
    - run: git commit -am "Create $FILENAME"
    - run: git push origin $GITHUB_REF_NAME
