name: Create Text File
description: Creates a text file very easy (Windows only)
branding:
 logo: 'file-text'
 color: 'blue'
inputs:
  text:
     description: 'The text to include in the file'
     required: true
     default: 'Hello world!'
  filename:
     description: 'The name of the file when saved'
     required: true
     default: 'file.txt'
  path:
     description: 'The path where to place the file'
     required: false
   overwrite:
     description: 'overwrite the file if it exists'
     required: false
     default: 'true'
runs:
  using: "composite"
  steps:
    - run: "@echo off"
      shell: cmd
    - name: Check whether overwriting value is true or false
      run: if %INPUT_OVERWRITE%==true (set INPUT_OVERWRITE= > nul) else (set INPUT_OVERWRITE=^>)
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Change to GitHub repository directory
      run: cd "${{ github.WORKSPACE }}"
      shell: cmd
    - name: Check for existence of path  
      run: "if not exist ${{ inputs.path}} (echo Path doesn't exist! Creating it... && mkdir ${{ inputs.path }}) else (echo Path exists!)"
      shell: cmd
    - name: Create text file
      run: "echo ${{ inputs.text }} >%INPUT_OVERWRITE% ./${{ inputs.path }}/${{ inputs.filename }}"
      shell: cmd
    - name: Set repository configuration
      run: | 
        git config --global user.name "${{ github.REPOSITORY_OWNER }}"
        git config --global user.email "${{ github.REPOSITORY_OWNER }}@users.noreply.github.com"
      shell: cmd
    - name: Include the new text file(s)
      run: "git add -A"
      shell: cmd
    - name: Create a commit for changes
      run: 'git commit -am "Create ${{ inputs.filename }}"'
      shell: cmd
    - name: Push the made changes to the remote
      run: "git push origin ${{ github.REF_NAME }}"
      shell: cmd
